version: '3'
services:
  catch22:
    image: themasterr/catch22:latest
    build: .
    container_name: catch22
    ports:
      - 8080:8080
    entrypoint: npm run mon
    environment:
      - PRIVATE_TOKEN=${PRIVATE_TOKEN}
      - GITLAB_HOST=${GITLAB_HOST}
    volumes:
      - ./app:/code/app
