---
apiVersion: v1
kind: Service
metadata:
  name: service-catch22
  labels:
    app.kubernetes.io/name: service-catch22
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: catch22
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catch22
  labels:
    app.kubernetes.io/name: catch22
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catch22
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catch22
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      containers:
      - name: catch22
        image: themasterr/catch22:latest
        ports:
        - containerPort: 8080
        # Setting the environment variable DEBUG we can see the headers sent
        # by the ingress controller to the backend in the client response.
        env:
        - name: PRIVATE_TOKEN
          value: ""
        - name: GITLAB_HOST
          value: ""
